version: "3"

tasks:
  migrate:
    desc: "Generate migrations db fies"
    cmds:
     - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations
  run:
    desc: "gRPC Run"
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yml


